const config = require('../../config');
const axios = require('axios');

// Helper delay function
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

// All supported companies
const companies = [
    '1win', 'betway', 'sportybet', 'premierbet', 'betika', 'wasafibet',
    '888sport', 'parimatch', '22bet', 'melbet', 'mozzart', 'mbet',
    'meridianbet', 'gsb', 'bet365', 'megapari', 'betpawa'
];

// Analysis phrases for variety
const analysisPhrases = [
    "Observing low blues (1.0x-1.5x) – pattern indicates possible burst soon.",
    "High volatility detected – consider early cashout at 2.0x.",
    "Trend shows increasing multiplier – safe exit at 2.5x.",
    "Two consecutive low rounds – next likely high. Target 5.0x.",
    "Red candles forming – risk level moderate. Cashout at 1.8x.",
    "Stabilising after drop – potential 3.0x within next 3 rounds.",
    "AI analysis: 85% chance of burst between 2.0x-4.0x.",
    "Market sentiment positive – aim for 6.0x but be ready to cashout.",
    "Historical data suggests 2.2x is a safe threshold.",
    "Watch for green spikes – they often precede a crash.",
    "Early crash detected – take profits quickly.",
    "Steady climb – consider holding for 3.0x+.",
    "Risk level: moderate – recommended cashout at 2.8x.",
    "High reward potential but be cautious.",
    "Pattern matches previous winning rounds."
];

// ==================== COMPLETE VIP MANUAL ====================
const vipManual = `
╭─── • 🥀 • ───╮
   ᴠɪᴘ ᴀᴠɪᴀᴛᴏʀ ᴍᴀɴᴜᴀʟ
╰─── • 🥀 • ───╯

━━━━━━━━━━━━━━━━━━━━━━━━━
🔰 *HOW TO USE VIP SIGNALS*
━━━━━━━━━━━━━━━━━━━━━━━━━

1️⃣ *View this manual*  
   Type: \`.aviator\`  
   → Displays this guide.

2️⃣ *Request signals for a specific company*  
   Type: \`.aviator <company> [number]\`  
   Example: \`.aviator 1win 5\`  
   → Generates **5 signals** for **1win**.  
   → If you omit the number, you get 1 signal.

   To see all supported companies, check the list at the end.

3️⃣ *How each signal is delivered*  
   - Every **2 minutes**, a new signal appears.  
   - Each signal contains:
     • Company name
     • Expected burst multiplier (e.g., 2.35x)
     • Confidence percentage (75‑99%)
     • Market analysis & recommended action
   - The message auto‑deletes after 5 minutes to keep chat clean.

━━━━━━━━━━━━━━━━━━━━━━━━━
🎯 *PLAYING STRATEGIES (with real examples)*
━━━━━━━━━━━━━━━━━━━━━━━━━

┌─── 🛡️ *STRATEGY 1: CONSERVATIVE (Low Risk)*
│  • Bet amount: 1,000 TZS
│  • Target: 1.5x – 2.0x
│  • How: When you see a signal for a company, open that site.
│         Place your bet. Watch the multiplier live.
│         As soon as it passes 1.5x, cash out.
│  • Example:
│      - Signal: 1win – expected 2.3x, confidence 88%
│      - You bet 1,000 TZS on 1win.
│      - Multiplier reaches 1.7x → you cash out.
│      - Profit = 1,000 × (1.7 – 1) = 700 TZS.
│  • Risk: Very low. You win small but consistently.
└────────────────────────

┌─── ⚖️ *STRATEGY 2: MODERATE (Balanced)*
│  • Bet amount: 2,000 TZS
│  • Target: 3.0x – 5.0x
│  • How: Look for signals with confidence >85% and analysis mentioning
│         "two consecutive low rounds" or "green spike". Place bet and
│         let it ride until 3.0x, then cash out.
│  • Example:
│      - Signal: betpawa – expected 4.2x, confidence 92%
│      - You bet 2,000 TZS on betpawa.
│      - Multiplier hits 3.8x → cash out.
│      - Profit = 2,000 × (3.8 – 1) = 5,600 TZS.
│  • Risk: Medium. You may lose some rounds, but wins cover losses.
└────────────────────────

┌─── 💎 *STRATEGY 3: AGGRESSIVE (High Risk / High Reward)*
│  • Bet amount: 500 TZS (small)
│  • Target: 10.0x – 20.0x
│  • How: Use only when analysis says "High reward potential" or
│         "Pattern matches previous winning rounds". Bet small and
│         hold until a very high multiplier.
│  • Example:
│      - Signal: sportybet – expected 15.7x, confidence 79%
│      - You bet 500 TZS on sportybet.
│      - Multiplier climbs to 12.4x → cash out.
│      - Profit = 500 × (12.4 – 1) = 5,700 TZS.
│  • Risk: High. Most rounds will crash early, but one big win can
│         give massive profit.
└────────────────────────

━━━━━━━━━━━━━━━━━━━━━━━━━
🧠 *VIP PRO TIPS*
━━━━━━━━━━━━━━━━━━━━━━━━━
✓ Always wait for the full signal – don't rush.
✓ Use a stop‑loss: if you lose 3 signals in a row, take a break.
✓ Keep track of your wins/losses with a small notebook.
✓ These signals are generated by advanced algorithms – treat them as
  high‑probability predictions, not guarantees.
✓ Play responsibly – never bet more than you can afford to lose.

━━━━━━━━━━━━━━━━━━━━━━━━━
📋 *SUPPORTED COMPANIES*
━━━━━━━━━━━━━━━━━━━━━━━━━
${companies.map(c => '• ' + c).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━
⏱️ *SESSION TIMING*
━━━━━━━━━━━━━━━━━━━━━━━━━
• Each signal is sent every 2 minutes.
• After your requested number of signals, the market closes for 30 minutes.
• You can start a new session after the cooldown.

_🥀 Trust the shadows, not the pilot. Good luck, VIP._
`;

module.exports = {
    name: "aviator",
    execute: async (conn, msg, args, { from, fancy, reply }) => {
        // If no arguments, show the manual only
        if (args.length === 0) {
            // Optionally send an image first (optional)
            const imageUrl = 'https://raw.githubusercontent.com/stanytz378/stanyimagesservers/refs/heads/main/IMG_1424.jpeg';
            await conn.sendMessage(from, {
                image: { url: imageUrl },
                caption: fancy(
                    `╭── • 🥀 • ──╮\n  ᴠɪᴘ ᴀᴠɪᴀᴛᴏʀ ᴘʀᴇᴅɪᴄᴛᴏʀ\n╰── • 🥀 • ──╯\n\n` +
                    `_ʀᴇᴀᴅ ᴛʜᴇ ᴍᴀɴᴜᴀʟ ʙᴇʟᴏᴡ ᴛᴏ ʟᴇᴀʀɴ ʜᴏᴡ ᴛᴏ ᴘʟᴀʏ._`
                ),
                contextInfo: {
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: config.newsletterJid,
                        newsletterName: "ɪɴꜱɪᴅɪᴏᴜꜱ ᴀᴠɪᴀᴛᴏʀ"
                    }
                }
            });
            return reply(vipManual);
        }

        // Parse company and count
        let company = args[0].toLowerCase();
        let count = parseInt(args[1]) || 1;
        count = Math.min(12, Math.max(1, count));

        // Validate company
        if (!companies.includes(company)) {
            return reply(fancy(`❌ ᴜɴᴋɴᴏᴡɴ ᴄᴏᴍᴘᴀɴʏ.\n\nꜱᴜᴘᴘᴏʀᴛᴇᴅ ᴄᴏᴍᴘᴀɴɪᴇꜱ:\n${companies.join(', ')}`));
        }

        // Send the main image first
        const imageUrl = 'https://raw.githubusercontent.com/stanytz378/stanyimagesservers/refs/heads/main/IMG_1424.jpeg';
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: fancy(
                `╭── • 🥀 • ──╮\n  ᴠɪᴘ ᴀᴠɪᴀᴛᴏʀ ᴘʀᴇᴅɪᴄᴛᴏʀ\n╰── • 🥀 • ──╯\n\n` +
                `📌 *ᴄᴏᴍᴘᴀɴʏ:* ${company.toUpperCase()}\n` +
                `🔢 *ꜱɪɢɴᴀʟꜱ:* ${count}\n` +
                `⏱️ *ᴛᴏᴛᴀʟ ᴛɪᴍᴇ:* ${count * 2} ᴍɪɴᴜᴛᴇꜱ\n\n` +
                `_ꜰᴏʟʟᴏᴡ ᴛʜᴇ ꜱɪɢɴᴀʟꜱ ᴄᴀʀᴇꜰᴜʟʟʏ._`
            ),
            contextInfo: {
                isForwarded: true,
                forwardedNewsletterMessageInfo: {
                    newsletterJid: config.newsletterJid,
                    newsletterName: "ɪɴꜱɪᴅɪᴏᴜꜱ ᴀᴠɪᴀᴛᴏʀ"
                }
            }
        });

        // Small pause before starting signals
        await delay(3000);

        // Send signals
        for (let i = 1; i <= count; i++) {
            const odds = (Math.random() * (4.5 - 1.2) + 1.2).toFixed(2);
            const confidence = Math.floor(Math.random() * (99 - 75) + 75);
            const phrase = analysisPhrases[Math.floor(Math.random() * analysisPhrases.length)];

            const signalText = fancy(
                `╭── • 📊 • ──╮\n  ᴠɪᴘ ꜱɪɢɴᴀʟ #${i} – ${company.toUpperCase()}\n╰── • 📊 • ──╯\n\n` +
                `🚀 *ᴇxᴘᴇᴄᴛᴇᴅ ʙᴜʀꜱᴛ:* ${odds}x\n` +
                `📊 *ᴄᴏɴꜰɪᴅᴇɴᴄᴇ:* ${confidence}%\n` +
                `💡 *ᴀɴᴀʟʏꜱɪꜱ:* ${phrase}\n\n` +
                `_ᴛʜɪꜱ ꜱɪɢɴᴀʟ ᴡɪʟʟ ᴀᴜᴛᴏ-ᴅᴇʟᴇᴛᴇ ɪɴ 5 ᴍɪɴᴜᴛᴇꜱ._`
            );

            const sentMsg = await conn.sendMessage(from, { text: signalText });

            // Auto-delete after 5 minutes
            setTimeout(async () => {
                try {
                    await conn.sendMessage(from, { delete: sentMsg.key });
                } catch (e) {}
            }, 300000);

            // Wait 2 minutes before next signal (except after last)
            if (i < count) {
                await delay(120000);
            }
        }

        // After all signals, send market closed message
        await delay(2000);
        await conn.sendMessage(from, {
            text: fancy(
                `╭── • 🔒 • ──╮\n  ᴠɪᴘ ᴍᴀʀᴋᴇᴛ ᴄʟᴏꜱᴇᴅ\n╰── • 🔒 • ──╯\n\n` +
                `✅ *${count} ꜱɪɢɴᴀʟ(ꜱ) ꜰᴏʀ ${company.toUpperCase()} ᴄᴏᴍᴘʟᴇᴛᴇᴅ.*\n` +
                `🕒 *ɴᴇxᴛ ᴀɴᴀʟʏꜱɪꜱ ɪɴ 30 ᴍɪɴᴜᴛᴇꜱ.*\n\n` +
                `_ᴛʀᴜꜱᴛ ᴛʜᴇ ꜱʜᴀᴅᴏᴡꜱ, ɴᴏᴛ ᴛʜᴇ ᴘɪʟᴏᴛ._`
            ),
            contextInfo: {
                isForwarded: true,
                forwardedNewsletterMessageInfo: {
                    newsletterJid: config.newsletterJid,
                    newsletterName: "ɪɴꜱɪᴅɪᴏᴜꜱ ᴀᴠɪᴀᴛᴏʀ"
                }
            }
        });
    }
};